### PR TITLE
Add updateSelectedAddress mutation resource

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What problem is this solving?
Adds a resource to update the selected address using `updateSelectedAddress` mutation.

#### How should this be manually tested?
Access [this workspace](https://lucas--checkoutio.myvtex.com/cart/add?sku=289) and proceed to the shipping step in Checkout.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Comment by lucasecdb** [comment]
where is my release bot? :cries-in-spanish:

**Comment by darlenedms** [comment]
Not related but I don't know if it's expected. I probably already had a checkout cookie with a product, so when I entered the cart, I see a ghost product with a NaN price:
Screen Shot 2020-04-16 at 4 39 57 PM
Screen Shot 2020-04-16 at 4 43 53 PM
It follows me to Checkout and when I try to get back to Cart through browser back button, Cart looks empty but then product appear. Minicart seems to have 2 products, so when I click it:
Screen Shot 2020-04-16 at 4 58 51 PM
I'll try to film the whole thing.

**Comment by darlenedms** [comment]
See what happens when I have two addresses:
Apr-16-2020 16-48-45
I cannot edit the older address.

**Comment by lucasecdb** [comment]
> Not related but I don't know if it's expected. I probably already had a checkout cookie with a product, so when I entered the cart, I see a ghost product with a NaN price

I saw that, it was my fault :sweat_smile: I used the wrong `skuId` in the add to cart URL, and that product didn't have a price registererd, so our GraphQL returned an error (`Cannot return null for non-nullable field Item.listPrice`). I'll fix it there.

**Comment by darlenedms** [comment]
Also wasn't clear what should I test 🤔 maybe improve the test steps description.

**Comment by lucasecdb** [comment]
oh! since this is just to add the mutation resource I didn't really know how to describe the test.

**Review by darlenedms — APPROVED** [review]

**Review by pedromtec — APPROVED** [review]
LGTM!

**Pull request merged**
